unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"


set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s

set -g mouse on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# creating special termainal-like panes
bind-key - split-window -v \; resize-pane -y 10 

set-option -g status-position top
# set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.0'

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

# display real tmux window names in Catppuccin theme
set -g @catppuccin_window_current_text "#{window_name}"
set -g @catppuccin_window_text "#{window_name}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
